path_classifiers:
  library:
    - "src/miniz"
    - "src/taglib"
extraction:
  cpp:
    prepare:
      packages:
        - "cmake"
        - "libspdlog-dev"
        - "libfmt-dev"
        - "qttools5-dev-tools"
        - "qtbase5-dev"
        - "libqt5svg5-dev"
        - "libtag1-dev"
        - "libtag-extras-dev"
        - "libgstreamer1.0-dev"
        - "libgstreamer-plugins-base1.0-dev"
        - "libpulse-dev"
    configure:
      command:
       - "cmake -DSPDLOG_USE_CPM=true ."